name: Deploy Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write  # Permite gravar no repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Verificar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Executar migrações do banco de dados
      - name: Run migrations (Production)
        run: npx knex migrate:latest --env development

      # Passo 5: Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Passo 6: Autenticar com Firebase
      - name: Authenticate with Firebase
        run: firebase use --project sysdevelop --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

      # Passo 7: Fazer deploy no Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          firebase use --project sysdevelop --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
