name: CI/CD Develop

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependências
      - name: Install dependencies
        run: |
          npm install
          npm install -g firebase-tools knex

      # Autenticar com Firebase
      - name: Authenticate with Firebase
        run: firebase use --project sysmain-df031 --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

           # Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Seleciona o site a ser efetuado o hosting
      - name: Select which Firebase to use
        run: firebase target:apply hosting develop sysdevelop

      # Autenticar com Firebase
      - name: Authenticate with Firebase
        run: firebase use --project sysdevelop --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

      # Fazer deploy no Firebase Hosting
      - name: Deploy to Firebase Hosting
<<<<<<< HEAD
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
=======
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
>>>>>>> b07cfd73a484831788beacd27e150ecbdd0133e0
