name: Deploy Main

on:
  schedule:
    - cron: '0 21 * * *'  # Todos os dias às 21:00 (UTC)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Executar migrações do banco de dados
        run: npx knex migrate:latest --env production
        env:
          DATABASE_URL: "postgresql://postgres.oxzbqtkdwwcoutyicwro:Audithorium!1505@aws-0-sa-east-1.pooler.supabase.com:6543/postgres"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase use --project sysmain-df031 --token ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Deploy to Firebase Hosting
        run: |
          firebase use --project sysmain-df031 --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
